services:
  - type: web
    name: telegram-bot-sneakers
    runtime: node
    repo: https://github.com/kimboneri/Conexion-telegrma-bot-con-render
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
